### ISSUE TITLE
Unicode Characters Not Working

### ISSUE THREAD

**Issue by BigRedBrent** [paypal/ipn-code-samples#103]
### General information

* Environment: Production
* Language, language version, and OS: php

### Issue description

Not sure where the problem is, but when trying to save characters that are supposed to be in unicode (such as a name with Russian letters), they are scrambled and also cause emails to be corrupted.

**Comment by xiaoleih41** [comment]
Please log into your PayPal account profile, under **my selling tools**,  click on **more options** under **button language encoding** and select **UTF-8**

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
