### ISSUE TITLE
Not getting any POST vars to return URL

### ISSUE THREAD

**Issue by TomasHurtz** [paypal/ipn-code-samples#106]
### General information

* Sandbox: 
* Apache php  

### Issue description

Using IPN to validate and in my form I have:

    <input type="hidden" name="cmd"  value="_xclick"/>	
    <input type="hidden" name="business" value="<?php echo $paypalbizemailaddress;?>"> 
    <input type="hidden" name="item_name" value="<?php echo $product ?>">
    <input type="hidden" name="currency_code" value="USD"> 
    <input type="hidden" name="amount" value="<?php echo $price;?>"> 
    <input type="hidden" name="custom" value="<?php echo $custom_data ;?>"> 
    <input type="hidden" name="item_number" value="<?php echo $itemId;?>">
    <input type="hidden" name="first_name" value="<?php echo $fname;?>">
    <input type="hidden" name="last_name" value="<?php echo $lname;?>">
    <input type="hidden" name="city" value="<?php echo $city;?>">
    <input type="hidden" name="country" value="US"> 
    <input type="hidden" name="night_phone_a" value="<?php echo $ctycode;?>"> 
    <input type="hidden" name="night_phone_b" value="<?php echo $phone;?>">
    <input type="hidden" name="email" value="<?php echo $email;?>">
    <input type="hidden" name="no_shipping" value="1"> 
    <input type="hidden" name="return"  value="success.php" />
    <input  type="hidden" name="notify_url" value="ipn.php" />
    <input  type="hidden"  name="cancel_return"  value="cancel.php" />
     <input type="hidden" name="rm" value="2">

I have IPN turned on in sandbox profile and pointing to my notify_url (ipn.php).  
I have Auto Return turned On and pointing to my return url (success.php).
All my URLs are HTTPS

This works fine and I receive the IPN data back to my ipn.php as POST and I can do required DB processing with it.  However, recently the POST stopped working to my return (success.php) URL. When  I can't get any POST at my return URL (success.php), which I need to be able to present a "Thank you for the order - your order is complete" message.

So, I have tried with PDT and it correctly returns the GET vars to success.php without issue, however I don't like the ugly querystring in the URL which can also be manipulated by user.  It looks like this:
           `success.php?amt=300.00&cc=USD&cm=2-%7C-4&item_name=productabc&item_number=102323732&st=Completed&tx=3PW6232xxxxxxx118529437`

Why have POST vars stopped coming to my return URL?  This form has been working without issue for 12 months, now it stops recently.  

I thought that was the purpose of the `rm` value "2" is to receive POST vars back to return URL (as described here: in method three https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1188

Is there an issue with PayPal or is this a result of some change I am not aware of?
Thanks

**Comment by xiaoleih41** [comment]
It sounds like the IPN feature might have been disabled on your account for whatever reason. Do you have a `DebugId` associated with one of your payment call or your sandbox email address for me to take a look at the account? As this is an open forum, you may want to submit a ticket to www.paypal-techsupport.com to provide more account specific information so that engineer over there can discuss exact detail with you.

**Comment by xiaoleih41** [comment]
Close this issue as a solution has been provided.
