### ISSUE TITLE
Unicode special characters in IPN callback message INVALID

### ISSUE THREAD

**Issue by patwoowong** [paypal/ipn-code-samples#108]
### General information

* Environment: Sandbox and Production
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: python 2.7.13 CentOS 7

### Issue description

I'm having an issue where if there are an unicode characters above a certain threshold (characters 128 and higher) in any of the IPN message fields the verification will fail with INVALID when responding to the URL below. What's even more confusing is that some characters work perfectly fine such as çèé. But any Japanese, Thai characters in any address or name fields will fail. 
 
Been banging my head against the wall on this problem. How should the response be crafted for a VERIFIED response? 
 
[https://ipnpb.sandbox.paypal.com/cgi-bin/webscr](https://ipnpb.sandbox.paypal.com/cgi-bin/webscr)

Below is an example of the raw message and the query parameters I send back.

Parameter in question: address_name=John%2520Smith%25u010D
Character in question: č

RAW from POST before cmd=_notify-validate is added: 
 
`payment_type=instant&payment_date=Tue%20Sep%2005%202017%2009%3A06%3A37%20GMT-0400%20%28EDT%29&payment_status=Completed&address_status=confirmed&payer_status=verified&first_name=John&last_name=Smith&payer_email=buyer@paypalsandbox.com&payer_id=TESTBUYERID01&address_name=John%20Smith%u010D&address_country=United%20States&address_country_code=US&address_zip=95131&address_state=CA&address_city=San%20Jose&address_street=123%20any%20street&business=seller@paypalsandbox.com&receiver_email=seller@paypalsandbox.com&receiver_id=seller@paypalsandbox.com&residence_country=US&item_name=something&item_number=AK-1234&quantity=1&shipping=3.04&tax=2.02&mc_currency=USD&mc_fee=0.44&mc_gross=12.34&mc_gross_1=9.34&txn_type=web_accept&txn_id=645269291&notify_version=2.1&invoice=abc1234&test_ipn=1&verify_sign=An5ns1Kso7MWUdW4ErQKJJJ4qi4-ARVPICt-ff0txK0os0cZYThEcI2P`
  
Quoted URL parameters:
 
`cmd=_notify-validate&payment_type=instant&payment_date=Tue%2520Sep%252005%25202017%252009%253A06%253A37%2520GMT-0400%2520%2528EDT%2529&payment_status=Completed&address_status=confirmed&payer_status=verified&first_name=John&last_name=Smith&payer_email=buyer@paypalsandbox.com&payer_id=TESTBUYERID01&address_name=John%2520Smith%25u010D&address_country=United%2520States&address_country_code=US&address_zip=95131&address_state=CA&address_city=San%2520Jose&address_street=123%2520any%2520street&business=seller@paypalsandbox.com&receiver_email=seller@paypalsandbox.com&receiver_id=seller@paypalsandbox.com&residence_country=US&item_name=something&item_number=AK-1234&quantity=1&shipping=3.04&tax=2.02&mc_currency=USD&mc_fee=0.44&mc_gross=12.34&mc_gross_1=9.34&txn_type=web_accept&txn_id=645269291&notify_version=2.1&invoice=abc1234&test_ipn=1&verify_sign=An5ns1Kso7MWUdW4ErQKJJJ4qi4-ARVPICt-ff0txK0os0cZYThEcI2P
 `

**Comment by xiaoleih41** [comment]
The easiest solution is to sign in to your account on PayPal.com, select "Profile and Settings" > select"My selling tools" > select "PayPal button language encoding" at the bottom of the screen > select "More Options" then select UTF-8 here for both encoding on your website (if you use it for your website, and calls to PayPal) and UTF-8 for IPNs. PayPal will then expect UTF-8, and send UTF-8.

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit if the issue hasn't been solved.

**Comment by imjeffparedes** [comment]
patwoowong please resubmit this. I experienced this just now due to my client's last name has **ö** in it.
I disabled ipn verification for now.

**Comment by patwoowong** [comment]
jeff, I fixed it by using UTF-8 encoding as per the above answer by xiaoleih41. Try the following making sure you UTF-8 encode the strings being passed.

```python
    verify_args = chain(IPN_VERIFY_EXTRA_PARAMS, request.form.iteritems())
    verify_string = '&'.join(
        ('%s=%s' % (param, quote_plus(value.encode('utf-8'), safe=':/')) for param, value in verify_args))
```
