### ISSUE TITLE
Not getting success Message its just giving 200 status code

### ISSUE THREAD

**Issue by RamizDevBatch** [paypal/ipn-code-samples#109]
hy i have implement all code and test it on simulator too , its working fine on simulator and when i hit link from postman its giving me 200 status code, but problem is this my code is not showing message of fail or success condition, because i want to implement some code in success condition, thank you

**Comment by overint** [comment]
Please edit your issue to follow the [template](https://github.com/paypal/ipn-code-samples/blob/master/.github/ISSUE_TEMPLATE.md)
You have not provided enough information for us to help you.

**Comment by RamizDevBatch** [comment]
$raw_post_data = file_get_contents('php://input');
        $raw_post_array = explode('&', $raw_post_data);
        $myPost = array();
        foreach($raw_post_array as $keyval)
            {
            $keyval = explode('=', $keyval);
            if (count($keyval) == 2) $myPost[$keyval[0]] = urldecode($keyval[1]);
            }

        $req = 'cmd=_notify-validate';
        if (function_exists('get_magic_quotes_gpc'))
            {
            	$get_magic_quotes_exists = true;
            }

        foreach($myPost as $key => $value)
            {
            if ($get_magic_quotes_exists == true && get_magic_quotes_gpc() == 1)
                {
                $value = urlencode(stripslashes($value));
                }
              else
                {
                $value = urlencode($value);
                }

            $req.= "&$key=$value";
            }

        // STEP 2: Post IPN data back to paypal to validate

        $ch = curl_init('https://sandbox.paypal/cgi-bin/webscr'); // change to [...]sandbox.paypal[...] when using sandbox to test
        curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $req);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
        curl_setopt($ch, CURLOPT_FORBID_REUSE, 1);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            'Connection: Close'
        ));

        // In wamp like environments that do not come bundled with root authority certificates,
        // please download 'cacert.pem' from "http://curl.haxx.se/docs/caextract.html" and set the directory path
        // of the certificate as shown below.
        curl_setopt($ch, CURLOPT_CAINFO, dirname(__FILE__) . '/cacert.pem');

        if (!($res = curl_exec($ch)))
            {
	            error_log("Got " . curl_error($ch) . " when processing IPN data");
	            curl_close($ch);
	            exit;
            }
        curl_close($ch);

        // STEP 3: Inspect IPN validation result and act accordingly
        if (strcmp($res, "VERIFIED") == 0)
            {
	            $item_name = $_POST['item_name'];
	            $item_number = $_POST['item_number'];
	            $payment_status = $_POST['payment_status'];
	            if ($_POST['mc_gross'] != NULL)
	                {
	                $payment_amount = $_POST['mc_gross'];
	                }
	              else
	                {
	                $payment_amount = $_POST['mc_gross1'];
	                }

	            $payment_currency = $_POST['mc_currency'];
	            $txn_id = $_POST['txn_id'];
	            $receiver_email = $_POST['receiver_email'];
	            $payer_email = $_POST['payer_email'];
	            $custom = $_POST['custom'];

	            echo "you win";

	        }
	        elseif (strcmp($res, "INVALID") == 0)
	            {
	            	echo "try again";
	            }


but its not giving me message in case of success or fail, its just giving me 200 status and i think code is not running after these line of code

 if (!($res = curl_exec($ch)))
            {
	            error_log("Got " . curl_error($ch) . " when processing IPN data");
	            curl_close($ch);
	            exit;
            }

can you please guide me how i can solve this ??

**Comment by overint** [comment]
You should check the error log to see if that is throwing an error. Try using our official samples:
https://github.com/paypal/ipn-code-samples/tree/master/php

**Comment by overint** [comment]
Did you manage to solve this?

**Comment by RamizDevBatch** [comment]
not yet , i m not getting notification from paypal when doing any action
like, do payment , payout etc

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by overint** [comment]
Have you tested using the sandbox?

**Comment by overint** [comment]
I'm going to close this as there was not enough detail provided. 
If you are still having issues, please open a new issue and follow the issue template correctly.
