### ISSUE TITLE
Ruby: OpenSSL::SSL::VERIFY_NONE

### ISSUE THREAD

**Issue by jgunnink** [paypal/ipn-code-samples#110]
https://github.com/paypal/ipn-code-samples/blob/391c6771e7f081a1e94f8e3fabc52f508d19cf3a/ruby/paypal_ipn_rails.rb#L27

Regarding the above line, I am getting failed SSL responses lately to my app, as I am using `http.verify_mode = OpenSSL::SSL::VERIFY_PEER`

Whilst I realise it's likely unrelated, I am just wondering if it is preferable to use `NONE` or `PEER`.

I am happy to open a PR to address this issue in the documentation if required.

Thank you :smiley:

**Comment by pp-randy** [comment]
Nice suggestion, a PR would be good. I'm always leaning towards more secure samples.   If you have other suggestions feel free to include them in the PR.

**Comment by overint** [comment]
Thanks for raising the PR, have merged it (#111).
