### ISSUE TITLE
Missing POST Data

### ISSUE THREAD

**Issue by MESWEB** [paypal/ipn-code-samples#116]
### General information

* Sandbox and Production
* PHP 7 

### Issue description

Always error:
PHP Fatal error:  Uncaught Exception: Missing POST Data in ... PaypalIPN.php:60 ...
  thrown in /PaypalIPN.php on line 60

**Comment by overint** [comment]
That would be a problem somewhere higher up that our verification class, since this exception is thrown only if the `$POST` superglobal is empty.  
Have you ensured your web server is correct passing post data to PHP?

**Comment by MESWEB** [comment]
No. My server is a shared server. But If I use this: 
```php
<?php
/**
 * https://www.experts-exchange.com/questions/28997357/echo-paypal-data-on-screen.html
 *
 * Show how to capture PayPal IPN error messages and write them into the log
 */
error_reporting(E_ALL);


// START THE OUTPUT BUFFER RIGHT AT THE TOP
ob_start();


/**
 * DO THE IPN PROCESSING HERE
 * USE PHP ECHO TO WRITE YOUR OWN ERROR MESSAGES
 */


// CAPTURE THE OUTPUT BUFFER RIGHT AT THE END
$ob = ob_get_clean();

// IF THERE IS ANYTHING IN THE BUFFER, SAVE IT
if ($ob) error_log($ob);
```
I see all variables with values in error log.

**Comment by overint** [comment]
Have you just using the code provided here?
https://github.com/paypal/ipn-code-samples/blob/master/php/example_usage.php

Do you get any errors?

**Comment by MESWEB** [comment]
Yes exactly if I use function verifyIPN the I get error about missing POST. This code is working fine and save all variables with values in test.txt file:
```php
require('PaypalIPN.php');
use PaypalIPN;
$ipn = new PaypalIPN();
// Use the sandbox endpoint during testing.
$ipn->useSandbox();
$verified = $ipn->verifyIPN();
$receiver_email = '';
if ($verified) {
    $handle = fopen("test.txt", "w");
    foreach ($_POST as $key => $value)
        fwrite($handle, "$key => $value \r\n");
    fclose($handle);
    foreach ($_POST as $key => $value)
        fwrite($handle, "$key => $value \r\n");

    $receiver_email = $_POST['receiver_email'];
    /*
     * Process IPN
     * A list of variables is available here:
     * https://developer.paypal.com/webapps/developer/docs/classic/ipn/integration-guide/IPNandPDTVariables/
     */
}

// Reply with an empty 200 response to indicate to paypal the IPN was received correctly.
header("HTTP/1.1 200 OK");
```

**Comment by MESWEB** [comment]
So that's seems Your Listener is not working properly?

**Comment by MESWEB** [comment]
Ok I was check PayPal message from this link https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNIntro/#id08CKFJ00JYK using POSTMAN application and everything working fine. This is look like PayPal got disabled POST messages from sandbox.

**Comment by MESWEB** [comment]
Problem solved.

**Comment by metabinaryio** [comment]
> Problem solved.

How you solved this problem?
