### ISSUE TITLE
POST verification IPN INVALID,  in google firebase functions 

### ISSUE THREAD

**Issue by elile** [paypal/ipn-code-samples#120]
### General information

* Environment: Production
* Google Firebase Functions, javascript, node.js 

### Issue description
I'm trying to implement ipn listener in google firebase functions but always getting response INVALID, 
when I testing my code with the IPN test simultor(on sandbox environment) it was worked OK with NULL date. 
When I testing on the sandbox environment with paypal button it's work OK
But on  production I always getting response INVALID.
My code is very similar to the googlecloudfunctions.js example
Thanks

**Comment by xiaoleih41** [comment]
Did you post your response to the correct URL? Please refer to [this page](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNTesting/#receiving-an-invalid-message-from-paypal) and troubleshoot this error.

**Comment by pp-randy** [comment]
The most common cause seems to be plus signs in dates and email addresses due to decoding issue which can cause these problems.  This is a community member provided code sample which is harder for us to support; however, if you provide the value of `formUrlEncodedBody` we can take a look as well.

**Comment by elile** [comment]
cmd=_notify-validate&txn_type=subscr_eot&subscr_id=I-PVPD5HU0MHN9&last_name=%25EC%25E5%25E9&residence_country=IL&item_name=Brollower%20App%20Subscription&mc_currency=USD&business=brollower.app%40gmail.com&verify_sign=ASa266U7Jp.-E6aey6OLApD6kFBrAiOZfDJeLvA8I30FeUVxBrTSFMQe&payer_status=verified&payer_email=eli.levi.1320%40gmail.com&first_name=%25E0%25EC%25E9&receiver_email=brollower.app%40gmail.com&payer_id=MYA733YPN8SJJ&item_number=b_a_s_eli_shwan&btn_id=146954739&custom=2468lelevi%40gmail.com&charset=windows-1255&notify_version=3.8&ipn_track_id=ff97aa16be71a

**Comment by pp-randy** [comment]
@elile Try changing your encoding to UTF-8 in your account profile IPN settings to see if that resolves the issue. If that toggle does not resolve your issue then reach out the PayPal Technical Support for assistance at https://www.paypal-techsupport.com/app/ask, due to the sensitive nature of production information.
