### ISSUE TITLE
Discrepancy in the information and IPN sample code

### ISSUE THREAD

**Issue by sonus21** [paypal/ipn-code-samples#125]
In the dev [doc](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNImplementation/#specs
) IPN verification URL is described as follows

> Send response messages back to PayPal:
> https://ipnpb.sandbox.paypal.com/cgi-bin/webscr (for Sandbox IPNs)
> https://ipnpb.paypal.com/cgi-bin/webscr (for live IPNs)

But in the [code](https://github.com/paypal/ipn-code-samples/blob/master/python/paypal_ipn.py) 

It's used from one of the following
```
VERIFY_URL_PROD = 'https://www.paypal.com/cgi-bin/webscr'
VERIFY_URL_TEST = 'https://www.sandbox.paypal.com/cgi-bin/webscr'
```

**Comment by overint** [comment]
The URLs in the code were/are the old URLs, which still work for backward compatibility however I have changed them over to the new URLs.
Thanks for the flag.

**Comment by sonus21** [comment]
As per the doc still seems to be inconsistent, we've to add User-Agent as well in the code.

**Comment by overint** [comment]
I have created a new issue for updating the samples to send a user agent, thanks.
