### ISSUE TITLE
Coldfusion IPN Returns "Connection Error"

### ISSUE THREAD

**Issue by Sadie** [paypal/ipn-code-samples#127]
### General information

* Environment: Sandbox

* Language, language version, and OS: ColdFusion9 on Windows Server 2008 R2

### Issue description

I am using the paypal_ipn.cfm exactly as presented here in the code samples.  Whether using the  IPN Simulator or my own sandbox cart, I successfully receive the data from PayPal and return it via URL.  But I can't get either a 'verified' or 'invalid' status.

The error_log.txt file contains "{ts '2018-03-20 09:33:37'}-Connection Failure" for my most recent send from the Simulator.

This is the related http request from the http.log in ColdFusion Administrator (in an attached text file):
[http_request.txt](https://github.com/paypal/ipn-code-samples/files/1829760/http_request.txt)

So, I receive neither a 'verified' or 'invalid' response, because apparently I'm not connecting.

In prior years I was able to successfully use "https://www.sandbox.paypal.com/cgi-bin/webscr?[attach string]", but as previously mentioned, I am using the code exactly as presented on this site with the new "https://ipnpb.sandbox.paypal.com/cgi-bin/webscr?[attach string]".

I am desperate to resolve this and appreciate any and all assistance.

**Comment by overint** [comment]
Hi Sadie
Are you able to test with the old URL?
I'm not familiar with CF, could it be a cert issue? https://stackoverflow.com/questions/20469194/coldfusion-https-connection-failure.

**Comment by overint** [comment]
Hi @Sadie, are you still having this issue?

**Comment by overint** [comment]
Closing this as no response, if you are still having the issue let us know.
