### ISSUE TITLE
About IPN validation parameters after 'VERIFIED' and 'Completed'

### ISSUE THREAD

**Issue by objcoding** [paypal/ipn-code-samples#130]
If PayPal meets the problem of inconsistent order amount and so on, what parameter do I need to return to PayPal, let him mark that this payment is wrong so as to refund the money to the customer?

**Comment by objcoding** [comment]
@overint Thank you for your answer, so I want to ask you how you deal with the problem of inconsistency after the'VERIFIED'. Is PayPal want to ask the merchant system to apply for a refund voluntarily? Instead of returning an error code after processing, perform a refund operation for PayPal.

**Comment by overint** [comment]
I'm still not sure what you mean by apply refund, and the `inconsistency `?
Can you explain further?

**Comment by objcoding** [comment]
@overint Sorry, my English is bad, that mean is "mc_gross is differ from merchant systmen order's fee"

**Comment by objcoding** [comment]
@overint if (verifyInfo.equals("VERIFIED")) { // 验证成功 success

            if ("Completed".equals(paymentStatus)) { // 支付成功 payment success

                if (!receiverEmail.equals("merchant's email")) {
                    
                    // 1. TODO deal with merchant system
                    
                    // 2. what shoul I do to tell paypal that then payment is Cheat？？？

                } else if (paymentAmount.equals("merchant's amount")) {
                    
                    // 1. TODO deal with merchant system

                    // 2. what shoul I do to tell paypal that then payment is Cheat？？？
                }
        }
}

**Comment by objcoding** [comment]
@overint 

if (verifyInfo.equals("VERIFIED")) { // 验证成功 success

            if ("Completed".equals(paymentStatus)) { // 支付成功 payment success

                if (!receiverEmail.equals("merchant's email")) {
                    
                    // 1. TODO deal with merchant system
                    
                    // 2. what should I do to tell paypal that then payment is Cheat？？？
                    // return "FAIL"?????
                } else if (paymentAmount.equals("merchant's amount")) {
                    
                    // 1. TODO deal with merchant system

                    // 2. what should I do to tell paypal that then payment is Cheat？？？
                    // return "FAIL"?????
                }
        }
}

**Comment by objcoding** [comment]
@overint 
`if (verifyInfo.equals("VERIFIED")) { // verify success

            if ("Completed".equals(paymentStatus)) { // payment success

                if (!receiverEmail.equals("merchant's email")) {

                    // 1. TODO deal with merchant system

                    // 2. what should I do to tell paypal that then payment is Cheat？？？
                    // return "FAIL"???

                } else if (!paymentAmount.equals("merchant's amount")) {

                    // 1. TODO deal with merchant system

                    // 2. what should I do to tell paypal that then payment is Cheat？？？
                    // return "FAIL"???
                }
        }
}
`

**Comment by objcoding** [comment]
@overint 

```
if (verifyInfo.equals("VERIFIED")) { // verify success

  if ("Completed".equals(paymentStatus)) { // payment success

    if (!receiverEmail.equals("merchant's email")) {

      // 1. TODO deal with merchant system

      // 2. what should I do to tell paypal that then payment is Cheat？？？
      
      // return "FAIL"???

    } else if (!paymentAmount.equals("merchant's amount")) {

      // 1. TODO deal with merchant system

      // 2. what should I do to tell paypal that then payment is Cheat？？？
      
      // return "FAIL"???
    }
  }
}
```

**Comment by overint** [comment]
> what should I do to tell paypal that payment is Cheat

The IPN is valid, it just means someone else tried to cheat your system. I would log the details and send an email, or similar. You do not need to notify paypal.

**Comment by objcoding** [comment]
@overint Thank you for taking the time to explain to me!

**Comment by overint** [comment]
No worries.
