### ISSUE TITLE
PYTHON Sample - all request are coming back with INVALID status

### ISSUE THREAD

**Issue by alfonsofoster** [paypal/ipn-code-samples#135]
* Environment: Sandbox

No Matter what I do, Im still receiving an INVALID status from the Sandbox when Im using the IPN Simulator.

But Im Paypal dev site says: "**IPN was sent and the handshake was verified.**"

I noticed that the same is happening with the PHP Sample( I saw an Issue opened for it!)

There is a "known Issue" for this?

Im getting crazy trying to find the root cause of this!

Any help with be appreciated! Thanks

**Comment by overint** [comment]
There are a few reports of this.
@paypal/ipn-sample-collaborators

**Comment by overint** [comment]
I'm closing this in favour of https://github.com/paypal/ipn-code-samples/issues/134
Feel free to continue the discussion there.
