### ISSUE TITLE
Return additionnal message value with donation

### ISSUE THREAD

**Issue by jbltx** [paypal/ipn-code-samples#18]
When we want to make a donation to someone on Paypal, we have to choose the amout of the donation, and a new page is loaded, where we could enter a message which will be joined with your donation.

1/ Is it possible to return the message in the IPN request (to notify_url) ?
2/ Is it possible to pre-write the message on my website, and submit it during the post form ?

**Comment by overint** [comment]
@jbltx 
I'm guessing since this is >2 years old you no longer need an answer. 
If so, please let me know so I can close this.

**Comment by overint** [comment]
I'm going to go ahead and close this. Feel free to tag me and i'll re-open it if you still need help.
