### ISSUE TITLE
$res splitting problem

### ISSUE THREAD

**Issue by MarioVillani** [paypal/ipn-code-samples#22]
Hi,
i noticed a problem when splitting $res for comparation.
Example works well when I use IPN simulator, but when i test with a payment in the sandbox PHP fails to split $res.
I fixed the problem with just 2 lines of code and i would like to sync it on this repo. How can i contribute to this repo? Thanks.

**Comment by overint** [comment]
Hi @MarioVillani, this is fixed by the new IPN listener sample.
