### ISSUE TITLE
Getting INVALID IPN status every time

### ISSUE THREAD

**Issue by digiogi** [paypal/ipn-code-samples#24]
I'm getting INVALID IPN status every time even the payment is made.

I'm using the php api.

Is there any way to do this properly?

**Comment by urgido** [comment]
Replace the existing with
if (strpos($res, "VERIFIED") !== 0){

**Comment by pp-randy** [comment]
Closing as a duplicate of https://github.com/paypal/ipn-code-samples/issues/51
