### ISSUE TITLE
ColdFusion IPN Listener example is incorrect

### ISSUE THREAD

**Issue by bryn51** [paypal/ipn-code-samples#27]
The example code for IPN Listener in ColdFusion is incorrect, I get Invalid every time.
I developed code that works, adapted from an example of code on another site:
 Dont seem to be able to include CF code in this post.

**Comment by MNU-497** [comment]
I had an issue but it was only on Coldfusion 8 server when using https. Coldfusion 8 server could not resolve the secure certificate. My Coldfusion 10 server handled it just fine. I ended up using CFX_HTTP5 on my Coldfusion 8 server because I insist on using a secure connection when I can.

**Comment by overint** [comment]
hi @bryn51, are you still having issues or am I able to close this issue?

**Comment by overint** [comment]
I'm going to go ahead and close this now.
