### ISSUE TITLE
Ruby On Rails sample

### ISSUE THREAD

**Issue by AmitPatel-BoTreeConsulting** [paypal/ipn-code-samples#36]
We have implemented recurring payment. We expect our application should receive notification after scheduled payment is processed.

We have been using [paypal-recurring](https://github.com/fnando/paypal-recurring) gem in  a subscription flow.

Any kind of help would be much appreciated.

**Comment by juwlee** [comment]
@AmitPatel-BoTreeConsulting are you looking for Ruby IPN code samples?

Please note that the paypal-recurring gem does not seem to be the one that PayPal supports. IPN support is implemented in [sdk-core-ruby](https://github.com/paypal/sdk-core-ruby). [The bottom of this docs](https://github.com/paypal/sdk-core-ruby/blob/2318c0db6070194ab2093ab3a2697a5e57badae7/DEV.md#usage-api-services) shows how IPN can be verified. Also, [this docs](https://github.com/paypal/merchant-sdk-ruby/blob/62939571e535d8ffed08b885bcd7c79146b391ce/merchant-sdk-ruby/samples/IPN-README.md) may help understand how IPN works for different PayPal APIs.
