### ISSUE TITLE
No HTTP 200 OK header in PHP IPN listener sample

### ISSUE THREAD

**Issue by tabalchi** [paypal/ipn-code-samples#37]
The PHP IPN listener sample doesn't include sending the HTTP 200 OK header as required. This just requires the following call before any other output is made (i.e. somewhere near the top): 

header('HTTP/1.1 200 OK');

Please check the other listener samples as well.

Not sending this was causing continued retries when I tested against sandbox.

**Comment by overint** [comment]
In my testing, the sandbox did not retry if the request failed, however this is correct and according to the paypal docs, the IPN should send an empty 200 response.

**Comment by pp-randy** [comment]
Thank you @overint, to add the only time you wouldn't want to provide a 200 would be if you needed the same IPN sent again. 

Usually I advise:

1. Validate the IPN
2. Store the IPN (If this fails return an error such as 500).
3. Return a 200 OK
4. Finish your business processing of the IPN. 

If you are providing a HTTP response that isn't a 200 and the sandbox is not sending the IPN again please let me know and I will look into that further.

**Comment by overint** [comment]
Closed as we have a new IPN listener sample.
