### ISSUE TITLE
IMMEDIATE ATTENTION REQUIRED: PayPal SSL Certificate Changes

### ISSUE THREAD

**Issue by solaceten** [paypal/ipn-code-samples#38]
Is this upcoming change likely to affect the PHP IPN code?

https://devblog.paypal.com/paypal-ssl-certificate-changes/

I need to know in advance - what testing can we perform

thanks

**Comment by tomwhipple** [comment]
As long as the machine your code is running on is capable of validating HTTPS SHA256 certificates, no change is required. If you are reasonably current on OS, OpenSSL & PHP versions you should be OK.

But you can test on the developer sandbox.
