### ISSUE TITLE
PHP: Assigning POST variables to local variable is redundant as you already assigned them to local $myPost

### ISSUE THREAD

**Issue by bg17aw** [paypal/ipn-code-samples#41]
Unless I am missing something, you already applied POST variables to local variable $myPost.

There is no need to create new local variables and assign them again (see line 113).

Maybe someone could create a pull request to fix this?

**Comment by heyallan** [comment]
I think that's because `$myPost` is still an array containing **first** incoming data.

At that point (#113), incoming data, has changed, and has been 'verified' by PayPal. They are not exactly the same. Although the variables at #113 are not necessarily the ones that change.

**Comment by overint** [comment]
Closing this as it relates to the old PHP sample.
