### ISSUE TITLE
Using ipn-php examples sometimes I receive certificate errors

### ISSUE THREAD

**Issue by Mimmo1961** [paypal/ipn-code-samples#43]
On my server I need to use
$cert = __DIR__ . "./cacert.pem";
curl_setopt($ch, CURLOPT_CAINFO, $cert);

BUT

only sometimes I receive "Can't connect to PayPal to validate IPN message: Peer certificate cannot be authenticated with known CA certificates"

cUrl version is 7.17.1

Someone could help me?

**Comment by quocbao1087** [comment]
Hi,
This is just a question for my limited knowledge.

I want to know what happens if we don't use cacert.pem.

What happens if I use this curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
and don't use curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1); curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
Thanks

**Comment by overint** [comment]
If you do not verify the certificate, anyone would be able to middleman the connection and sniff the IPN data.  Unless there is a specific reason why you cannot validate the cert (such as a debugging proxy) you should.
