### ISSUE TITLE
PHP magic_quotes_gpc is deprecated

### ISSUE THREAD

**Issue by heyallan** [paypal/ipn-code-samples#44]
> This feature has been DEPRECATED as of PHP 5.3.0 and REMOVED as of PHP 5.4.0.

Reference: http://php.net/manual/en/info.configuration.php#ini.magic-quotes-gpc
Used in: https://github.com/paypal/ipn-code-samples/blob/master/paypal_ipn.php#L28

**Comment by TWR-Dodge** [comment]
I do not think it is a bug as it checks to see if the function exists and if it is true then it does .... and if it isn't true then it does ..... Isn't that script so it can be used for different versions of php?

**Comment by gomonkey** [comment]
magic_quotes_gpc is deprecated but not get_magic_quotes_gpc
http://php.net/manual/en/function.get-magic-quotes-gpc.php

**Comment by heyallan** [comment]
@gomonkey You got a point!

**Comment by heyallan** [comment]
> `magic_quotes_gpc` is deprecated, but not `get_magic_quotes_gpc`
http://php.net/manual/en/function.get-magic-quotes-gpc.php

My bad.
