### ISSUE TITLE
IPN Failures, getting 404 

### ISSUE THREAD

**Issue by michelewindsor** [paypal/ipn-code-samples#47]
I am using a plugin called My tickets,  and sometimes the notifications via IPN come through from paypal and other times I go to the history page and see 404 in the history for the transactions.  Any ideas?   

From first glance,  my URL is http and paypal is resending in https.  However,  when I setup my IPN url with paypal I did not add https.   

I have roughly 10 people that cannot get tickets emailed because the plugin isn't getting a confirmation. 

Thanks everyone!
Michele

**Comment by pp-randy** [comment]
I advise setting up https, some best practices from the PayPal Merchant Technical Support team can be found here: https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1389&expand=true&locale=en_US

However, I do not believe the URL should be changed during the IPN retry so I advise you also submit a ticket to PayPal Merchant Technical Support here for further assistance with this issue: https://www.paypal-techsupport.com/app/ask/
