### ISSUE TITLE
Using ipn-code-samples VB getting the error Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Superitum** [paypal/ipn-code-samples#48]
Hi

The code used to work not to long ago and I have used the code exactly as in the example but on the line "Dim streamOut As StreamWriter = New StreamWriter(req.GetRequestStream(), Encoding.ASCII)" the code throws the error (The request was aborted: Could not create SSL/TLS secure channel.). Firewall is disabled and HTTP and HTTPS is allowed through Windows Firewall. 

Any suggestions?

**Comment by pp-randy** [comment]
Is this happening when posting back to PayPal? Is this in Sandbox or Live?

**Comment by Superitum** [comment]
Yes it's happening when posting back to PayPal. Sandbox

**Comment by pp-randy** [comment]
Its probably related to the TLS updates.  Can you review https://github.com/paypal/tls-update ?

**Comment by Superitum** [comment]
Jip also assumed it might have something to do with that, one would hope that the available samples are also updated after such changes. 
Will have a look at the tls-update thank you.

**Comment by Superitum** [comment]
The .Net Framework version seems fine: 
>NetFrameworkVersions.exe
_v2.0.50727  2.0.50727.5420  SP2
v3.0  3.0.30729.5420  SP2
v3.5  3.5.30729.5420  SP1
v4
  Client  4.5.50709
  Full  4.5.50709
v4.0
  Client  4.0.0.0_

But the TlsCheck fails with an error:
>TlsCheck.exe
_
Unhandled Exception: System.Net.WebException: The remote name could not be resol
ved: 'tlscheck.chargify.com'
   at System.Net.HttpWebRequest.GetResponse()
   at ConsoleApplication1.Program.Main(String[] args)_

I managed to ping chargify.com but host could not be found when pinging tlscheck.chargify.com

**Comment by Superitum** [comment]
Issue Resolved!
1. I upgraded the project to .Net Framework 4.5
2. Added this line to the listener code:
`System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12`

Regards

**Comment by pp-randy** [comment]
Awesome @Superitum !!!
