### ISSUE TITLE
Java Sample

### ISSUE THREAD

**Issue by theyuv** [paypal/ipn-code-samples#49]
Is there sample code in the Java language?

**Comment by theyuv** [comment]
Sorry, I see now in the documentation that there is not sample code for Java.
Is there a particular reason for this?

**Comment by pp-randy** [comment]
This isn't a standalone sample but maybe this could help https://github.com/paypal/merchant-sdk-java/blob/master/merchantsample/src/main/java/com/sample/ipn/IPNListenerServlet.java

**Comment by chenjianjx** [comment]
@pp-randy , the url you gave belongs to a deprecated sdk.  Is there any sample base on the official sdk, the PayPal-Java-SDK ?
