### ISSUE TITLE
PHP - Impossible to use sandbox

### ISSUE THREAD

**Issue by MxWayGamer** [paypal/ipn-code-samples#50]
Hello,
I use your php script for my ipn. It work perfectly when i don't use sandbox. 

But when i would like use sandbox and make USE_SANDBOX at 1. it don't work. I have this error : "Can't connect to PayPal to validate IPN message: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure ".

Do you know how i can use sandbox for test my script when I have "strcmp ($res, "VERIFIED") == 0".

Thanks you

**Comment by pp-randy** [comment]
Sandbox will not accept SSLv3 connections as explained here: https://github.com/paypal/tls-update.  Please review it and let me know if you have further questions, for compliance reasons, this change is also coming to Production in the future.

**Comment by MxWayGamer** [comment]
I don't all understand. I try to add the line in my script but i have this error : Unknown SSL protocol error in connection to tlstest.paypal.com:443

**Comment by pp-randy** [comment]
Most likely your openssl is not updated to a version to handle TLS 1.2.  openssl needs to be 1.0.1c or higher.  This thread might also be helpful https://github.com/paypal/PayPal-PHP-SDK/issues/484.
