### ISSUE TITLE
IPN SSL connect error

### ISSUE THREAD

**Issue by dannyhtek** [paypal/ipn-code-samples#53]
Hello.

I'm constantly getting the following errorcode in my ipn.log

> [2016-06-03 23:12 Europe/Amsterdam] Can't connect to PayPal to validate IPN message: SSL connect error
> [2016-06-03 23:12 Europe/Amsterdam] Can't connect to PayPal to validate IPN message: SSL connect error

This has been happening voor 5 days straight in a row, while it used to work before then. I tried switching PHP version and I even bought a SSL certificate. This did not solve my problem.

Is anyone else having the same issue? Did PayPal change something? They're not responding on Twitter. PayPal is really takin' the piss.

Any help would be appreciated.

**Comment by pp-randy** [comment]
Most likely related to TLS changes, more here: https://github.com/paypal/tls-update

**Comment by dannyhtek** [comment]
What do I have to change inside the code to make it work? I mean, the following code should work just fine:
`curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
`

**Comment by pp-randy** [comment]
Its not a code change. Please review the PHP section of the previous URL provided here: https://github.com/paypal/tls-update#php

Are you able to run the test it is suggesting?

**Comment by dannyhtek** [comment]
No I;m not :( I only have access to DirectAdmin.

**Comment by pp-randy** [comment]
Can you confirm you are facing this issue in sandbox and not production?

**Comment by dannyhtek** [comment]
Well I'm using sandbox for testing. Not sure if it works in production..

**Comment by pp-randy** [comment]
Currently this shouldn't impact production until June 2017 as indicated here: https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1914&expand=true&locale=en_US

However, most likely you will need a cURL update.

**Comment by dannyhtek** [comment]
I think I have found the problem. When I set my PHP version to native, I get the following check results:
TLS version:TLS 1.0
SSL version:NSS/3.19.1 Basic ECC

Whenever I set the PHP version to 5.5, I get the following check results:
TLS version:TLS 1.2
SSL version:OpenSSL/1.0.1e

**Comment by pp-randy** [comment]
@dannyhtek were you test against your 5.5 version?

**Comment by littlehawk** [comment]
Same problem for me.
I have verify my CURL version that is NSS/3.19.1 Basic ECC. 
This version included support for TLS v1.2. 
So i simply add this value:
`curl_setopt($ch, CURLOPT_SSLVERSION, 6);`

after:
`curl_setopt($ch, CURLOPT_POSTFIELDS, $req);`
and before:

`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1)`

Now all works perfectly!!!!

**Comment by pp-randy** [comment]
Closing the issue for now. Again more on these security changes can be found here: https://github.com/paypal/tls-update
