### ISSUE TITLE
No IPN log Internal Server Error with the PHP version

### ISSUE THREAD

**Issue by benoit1980** [paypal/ipn-code-samples#56]
Hello,

I have set the IPN simulator from paypal to:
"Transaction type" = Cart checkout

"Payment _ type" = instant

Left all the details as they are and pointed the ipn to the right url on my server.
All I get is Internal Server Error  from the ipn simulator. No logs, nothing to show.

Anyone with this problem?

Thank you.

**Comment by heidgert** [comment]
I got the internal server error a couple of times. Turned out that I had been logged out every time. Refresh the entire page to make sure that you are still signed in.

**Comment by benoit1980** [comment]
Thank you. I have changed code since so I won't be able to tell you if the problem is gone sorry.
