### ISSUE TITLE
Issue with encode/decode

### ISSUE THREAD

**Issue by MrMegamind** [paypal/ipn-code-samples#61]
Hi
I coped and used the script but did not work until I changed  rawurlencode and rawurldecode
It took me some time to figure this out, Dont you think we should use these functions in source?

**Comment by galinski** [comment]
Same here
:+1:

**Comment by overint** [comment]
Hey @MrMegamind and @galinski 
There's a new OOP PHP sample that should be much easier to use and understand.
I'm going to close this since it relates to the old sample. Thanks for your contribution!
