### ISSUE TITLE
example_usage.php

### ISSUE THREAD

**Issue by stf9** [paypal/ipn-code-samples#65]
Shouldn't the 200 response should be sent before the IPN attempts to verify, not at the end of the script: https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNImplementation/

1. Your listener listens for the HTTP POST IPN messages that PayPal sends with each event.
2. After receiving the IPN message from PayPal, your listener returns an empty HTTP 200 response to PayPal. Otherwise, PayPal resends the IPN message.
3. Your listener sends the complete message back to PayPal using HTTPS POST.
4. PayPal sends one of the following words back to your listener

**Comment by overint** [comment]
Yep, it does explain that in the docs, however there is a lot of ambiguity. @pp-randy [suggests the following here](https://github.com/paypal/ipn-code-samples/issues/37#issuecomment-250193508):

> Usually I advise:
> 
> Validate the IPN
> Store the IPN (If this fails return an error such as 500).
> Return a 200 OK
> Finish your business processing of the IPN.
>

**Comment by stf9** [comment]
That makes sense, thanks. I think I was was just confused because the IPN simulator was getting an error if I didn't have the 200 before the verify, but now I realize it's because I had a die() in a different part of my code so it never gets to the 200.

**Comment by overint** [comment]
No worries, glad you got it fixed.
