### ISSUE TITLE
ipn response invalid on cell phone but Verified on Laptop.

### ISSUE THREAD

**Issue by clovisHub** [paypal/ipn-code-samples#70]
### Required Information
My listerner looks exactly the same as in your sample. but I am receiving invalid when I am testing my IPN payment on cell phone while it is Valid on laptop. Wha tcould be wrong?Why is it not working on cell phone?
- Which lanuage sample:  C# MVC
- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

**Comment by overint** [comment]
Not sure I understand your problem, do you mean payments from the mobile app?

**Comment by clovisHub** [comment]
I meant a web application. Not a mobile app. my web link is something like https://www.webname.domaine.
if I open it on my laptop from any browser (either google chrome, internet explorer or firefox) and process the payment. it is working fine. the response is verified.

but whenever I open chrome on any cell phone, and use the same link, after processing the payment, the response is Invalid.

below is my listener...

public ActionResult NotifiedFromPayPal()
        {

            

            string strSandbox = "https://www.sandbox.paypal.com/cgi-bin/webscr";
            try
             {
                 ServicePointManager.Expect100Continue = true;
                 ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls
                        | SecurityProtocolType.Tls11
                          | SecurityProtocolType.Tls12
                        | SecurityProtocolType.Ssl3;

                
                HttpWebRequest req = (HttpWebRequest)WebRequest.Create(strSandbox);

                ViewBag.original = req;

                req.Method = "POST";
                req.ContentType = "application/x-www-form-urlencoded";

                byte[] param = Request.BinaryRead(Request.ContentLength);
                string  strRequest = Encoding.ASCII.GetString(param);
                ViewBag.myReq = strRequest;
                strRequest += "&cmd=_notify-validate"; 
               
                req.ContentLength = strRequest.Length;

            

                // Send request
                
                StreamWriter streamOut = new StreamWriter(req.GetRequestStream(), System.Text.Encoding.ASCII);
                streamOut.Write(strRequest);
                
                streamOut.Flush();
                streamOut.Close();

                // get it back
                StreamReader streamIn = new StreamReader(req.GetResponse().GetResponseStream());
                string strResponse = streamIn.ReadToEnd();
                streamIn.Close();

                ViewBag.streamIn = strResponse; 

                string response = strResponse;

                if (response == "INVALID")
                {
                    
                   

                }

                if (response == "VERIFIED")
                {
                            //Some codes here to retrieve some values
               }
     }

**Comment by clovisHub** [comment]
I will really appreciate if anybody can help me figure out how to solve this issue

**Comment by pp-randy** [comment]
@clovisHub can you provide the sandbox transaction id?  I will see if I can find some sandbox logs to help explain the issue.

**Comment by clovisHub** [comment]
Yes of course. Transaction ID: 3GR616630D807781D

**Comment by pp-randy** [comment]
Hi Clovis,

Can you try verification against https://ipnpb.sandbox.paypal.com/cgi-bin/webscr

I couldn't find your post back log from the transaction.  Would you be able to get me a ipn_track_id from a failed verification attempt?  It can be a different transaction if easier.  The ipn_track_id is part of the IPN data sent to you.

**Comment by overint** [comment]
Sorry, i've been traveling and was not able to respond. 
You should dump the incoming IPN to a log or similar and then post it here, that way we will be able to help you much easier.

**Comment by clovisHub** [comment]
I was trying to solve it myself, but it didn't work. I will create a log file and post it here. 

I tried this to check if I was getting anything from sandbox to be sure at least I was receiving a response before adding this following : strRequest = "cmd=_notify-validate&" + strRequest; 

I just tried to see if the array has some values. So, I did this:

HttpWebRequest req = (HttpWebRequest)WebRequest.Create(strSandbox);

 byte[] param = Request.BinaryRead(Request.ContentLength);

ViewBag.myReq =  param.Length;

The ViewBag.myReq has like result : 0 when I used a cell phone browser to do the purchase. But, it was 1048 when I tried the same thing with a laptop. That made me to think as if I am not getting anything back to my website after the payment is processed on cell phone. I wanted just to let you know maybe you would figure out what I need to do quicker.
Anyway I will do as you asked, if it still would be necessary.

**Comment by overint** [comment]
My guess is that the IPN postback URL is not set correctly, or something is going wrong with your form. Do you use the same code to create the transaction for desktop and mobile?

**Comment by clovisHub** [comment]
Yes I did use the same code for both. This is how I set up my form. this is my form:

@model IPNpaypal.Models.OnlineOrderModel

<div class="col-md-3">

    @*<span><img src="~/Images/Western-Union-icon.png"/></span>*@

    <h4>Order trial</h4>

    @using (Html.BeginForm("ValidateCommand", "Home"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ClientFirstName, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClientFirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ClientFirstName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ClientLastName, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClientLastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ClientLastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StreetAddress, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StreetAddress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StreetAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Apt, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Apt, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Apt, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.QuantityPurchased, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.QuantityPurchased, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.QuantityPurchased, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Send" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

</div>

And this the checkout form:

@model IPNpaypal.Models.PayPalData
@{
    ViewBag.Title = "ValidateCommand";
}
 

<h2>ValidateCommand</h2>

<div>
    <form id="hiddenform" action=@Model.actionURL method="post">

        @Html.HiddenFor(model => model.cmd)
        @Html.HiddenFor(model => model.business)
        @Html.HiddenFor(model => model.@return)
        @Html.HiddenFor(model => model.cancel_return)
        @Html.HiddenFor(model => model.notify_url)
        @Html.HiddenFor(model => model.currency_code)
        @Html.HiddenFor(model => model.item_name)
        @Html.HiddenFor(model => model.amount)
        @Html.HiddenFor(model => model.quantity)
        @Html.HiddenFor(model => model.txn_id)
        @Html.HiddenFor(model => model.custom)
        @Html.HiddenFor(model => model.item_number)


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Checkout" class="btn btn-success" />
            </div>
        </div>
    </form>

    <p style="text-align: center">

    </p>
</div>

**Comment by overint** [comment]
No, I mean the paypal HTML form, or other method (encoded URL, checkout) you use to create the request to paypal after a user's purchase is processed.

**Comment by overint** [comment]
Did you get a chance to get that code?

**Comment by overint** [comment]
I'm going to close this in a few days if there is no response, thanks.

**Comment by overint** [comment]
No worries, I'll leave it open then. Thanks.

**Comment by overint** [comment]
Hey clovis, did you end up working this out?

**Comment by clovisHub** [comment]
Hi overint. I am really sorry to reply after months. But I got it fixed you should have updated... Nothing was wrong with Paypal response. All this trouble was just caused by a duplicated code I had in it one model (class) and also in the controller that was calling this class... All the code I posted above works fine, there were no error except in what I did not post here and kept in secret. 
Thank you much for your support! :)

**Comment by overint** [comment]
No worries!
