### ISSUE TITLE
$_POST array cleared after calling the class (php) in WordPress

### ISSUE THREAD

**Issue by Mickhael** [paypal/ipn-code-samples#71]
Good day! Apologize in advance for my english.
I'm a beginning programmer, and not fully understand. I added a class and its call as shown in the example, but after returning from sandbox paypal $_POST array is empty. What is it can be connected and what am I doing wrong? 
I'm afraid to be tested for live before to will work in a sandbox.

**Comment by Mickhael** [comment]
always fires
`if ( ! count($_POST)) {
            throw new Exception("Missing POST Data");
        }`

**Comment by jaypatel512** [comment]
To execute the payment you need something like this: https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/ExecutePayment.php

**Comment by overint** [comment]
Are you sure you are posting back to the correct URL? 
That error means that the $_POST was empty (eg, no data or it was not a post request).

**Comment by overint** [comment]
I'm going to close this in a few days if there is no response, thanks.
