### ISSUE TITLE
Code is not working on php 5.3.x

### ISSUE THREAD

**Issue by acdmail** [paypal/ipn-code-samples#76]
### Required Information

- Which language sample: PHP
- Mode (Sandbox/Live): Both
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
It seems that the code is not compatible with php 5.3.x which for example ships by default with Redhat/Centos 6.x
The issue is related to short syntax for arrays introduced by php 5.4 and used in the code, below two lines  result in syntax error in php 5.3

$myPost= [];
...
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Connection: Close']);

But are working once corrected like:

$myPost= array();
...
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Connection: Close'));

Thanks

**Comment by overint** [comment]
Thanks for the heads up, we'll get it fixed ASAP.

**Comment by overint** [comment]
Fixed by https://github.com/paypal/ipn-code-samples/commit/e28f35f4cd91f0aa1a5ee8f4c3ed5f175e022570

**Comment by acdmail** [comment]
hi,
Thanks for fast fixing but fixed partially only, maybe I was not clear enough during the issue description

This one in the code still causing the syntax error:
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Connection: Close']);

and should look like:

curl_setopt($ch, CURLOPT_HTTPHEADER, array('Connection: Close'));

Thanks

**Comment by overint** [comment]
Fixed, thanks!
