### ISSUE TITLE
Php outputs a warning because of the usage of use PaypalIPN;

### ISSUE THREAD

**Issue by lordspace** [paypal/ipn-code-samples#77]
### Required Information

- Which language sample:
php

### Issue Description
Php outputs a warning because of the usage of use PaypalIPN;

`Warning: The use statement with non-compound name 'PaypalIPN' has no effect in /htdocs/projects/paypal_ipn/index.php on line 6`

**Comment by overint** [comment]
Are you sure you copied the example correctly? If so, what version of PHP are you running?

**Comment by lordspace** [comment]
Yep. 
Php 5.6

**Comment by overint** [comment]
I tested it on a PHP 5.6 environment and it seems to work fine, what is the complete version?

**Comment by overint** [comment]
Did you solve the issue?

**Comment by lordspace** [comment]
I removed the "use Paypal or PaypalIPN" and the warning disappeared.

**Comment by jwieder** [comment]
Old issue but for others viewing this, but @lordspace's approach above could result in problems. The correct approach would be to declare (any) namespace within the listener file. I'm going to fork this project & push an update that will demonstrate the solution.

**Comment by pp-randy** [comment]
Thank you for the pull @jwieder it has been merged.
