### ISSUE TITLE
PHP 5.6 getting curl error 77

### ISSUE THREAD

**Issue by trenidor** [paypal/ipn-code-samples#78]
### Required Information

- Which language sample: php
- Mode (Sandbox/Live): sandbox
- PayPal-Debug-ID(s) (from any logs):??

### Issue Description

I keep getting: 
PHP Fatal error:  Uncaught exception 'Exception' with message 'cURL error: [77] Problem with the SSL CA cert (path? access rights?) ...paypalIPN.php:107

It was weird because I had it working for a day or two then put it on pause for a few days until I was ready to make a few changes before the final version and before I changed anything I ran a test and got this error ever since. 

I've verified the SSL with my webhost and I switched from php 5.4 to 5.6 but still get that problem on both the paypal IPN simulator and paypal sandbox buttons.

**Comment by overint** [comment]
Did you download the cert bundle correctly? I should be in /cert/cacert.pem, otherwise it will throw an error.

**Comment by trenidor** [comment]
Should that be in my root directory or on the same level as paypalIPN.php?

**Comment by overint** [comment]
It should be the same directory structure as the repo, i.e. 
-ipnclass
--certs
---cacert.pem
--ppaypalIPN.php

**Comment by trenidor** [comment]
then it appears to be in the correct path...

**Comment by trenidor** [comment]
Weird thing happened... I was doing some debugging and decided, what the hell, I'll just see if it will dump the full path to me in the error. 

I changed line 105 to :             $errstr = curl_error($ch) . __DIR__ .  '"/cert/cacert.pem"';

and suddenly it stopped throwing an error. Any explaination?

**Comment by overint** [comment]
No idea, that's strange. 
You could try using your php installations built in cert bundle (if it's up to date).

**Comment by overint** [comment]
Did you solve the issue?

**Comment by trenidor** [comment]
Ya, though I don't understand why that worked.
