### ISSUE TITLE
Getting INVALID status every time can you please help me out for this

### ISSUE THREAD

**Issue by prpatel24** [paypal/ipn-code-samples#8]
I am getting INVALID IPN status every time for PayPal response following is mine vb.net code can you please help me out where i am doing wrong thing......
============================================================

            Dim req As HttpWebRequest = Nothing
            Dim IsPaypalInTestMode As Boolean = True
            If IsPaypalInTestMode = True Then
                ' Create the request back
                req = DirectCast(WebRequest.Create("https://www.sandbox.paypal.com/cgi-bin/webscr"), HttpWebRequest)
            Else
                req = DirectCast(WebRequest.Create("https://www.paypal.com/cgi-bin/webscr"), HttpWebRequest)
            End If

            AddWebProxyOnLocalServer(req)
            'Set values for the request back
            req.Method = "POST"
            req.ContentType = "application/x-www-form-urlencoded"
            Dim Param() As Byte = Request.BinaryRead(HttpContext.Current.Request.ContentLength)
            Dim strRequest As String = GetPaypalResponseString(Request.Form.ToString)
            strRequest = "cmd=_notify-validate&" & strRequest
            req.ContentLength = strRequest.Length

            'Send the request to PayPal and get the response
            Dim streamOut As StreamWriter = New StreamWriter(req.GetRequestStream(), Encoding.ASCII)
            streamOut.Write(strRequest)
            streamOut.Close()

            ''''Write In File
            WriteInFile("Acknowledgment Sent At : " & Now)
            WriteInFile("Acknowledgment Sent to PayPal : " & strRequest & vbNewLine)

            Dim streamIn As StreamReader = New StreamReader(req.GetResponse().GetResponseStream())
            Dim strResponse As String = streamIn.ReadToEnd()
            streamIn.Close()

            ''''Write In File
            WriteInFile("Acknowledgment Response by PayPal Received At : " & Now)
            WriteInFile("Acknowledgment Response by PayPal : " & strResponse & vbNewLine)
            WriteInFile("----------------------------------------------")

            If strResponse.ToUpper = "VERIFIED" Then
                streamIn.Close()
                streamOut.Close()
                Return True
            Else
                streamIn.Close()
                streamOut.Close()
                Return False
            End If

============================================================

**Comment by pp-randy** [comment]
Closing due to age of issue.
