### ISSUE TITLE
Google Apps Script: Escaping plus (+) with (%2B) in url mismatches payload with original contents and results in INVALID PayPal response.

### ISSUE THREAD

**Issue by morphcatalyst** [paypal/ipn-code-samples#89]
### General information

* Environment: Sandbox (Not tested in Prod yet)
* `PayPal-Debug-ID` values: In description below
* Language, language version, and OS: Google Apps Script

### Issue description
**Using Google script in url:**
https://github.com/paypal/ipn-code-samples/blob/master/javascript/googlescript.js

**Compared PayPal post request (e) variable with payload response:**
"contents":"transaction_subject=&payment_date=`03%3A15%3A10+May+06%2C+2017+PDT`&txn_type=...&ipn_track_id=6d3a5808b1483"...

payload=cmd=_notify-validate&transaction_subject=&payment_date=`03%3A15%3A10%2BMay+06%2C+2017+PDT`&txn_type=...&ipn_track_id=6d3a5808b1483...

**Result response from Paypal: INVALID**
In the above strings, first (+) is replaced with (%2B) and hence no match.

**Solution:**
Removing line 11 ` payload = payload.replace("+", "%2B");` fixes the issue and validates the PayPal response.

**Comment by pp-randy** [comment]
@morphcatalyst thank you for the information.  Would you be interested in submitting a pull request?

**Comment by overint** [comment]
That's very strange, since it was previously required.
Can you confirm this is still the correct solution, if so I will create a pull request.
Thanks

**Comment by morphcatalyst** [comment]
Hi,

Sorry wasnt able to create a pull requedt myself, was a bit busy and dont
have full knowledge on how to do it.

I can confirm my code works without that line.

Thanks,
Amit

**Comment by overint** [comment]
Have opened a pull request (#93), and will merge it if no one has any issues.
