### ISSUE TITLE
Missing Post Data

### ISSUE THREAD

**Issue by TychaK** [paypal/ipn-code-samples#92]
Using Php To implement Paypal Instant Payment Notification through this code, I get the following error

"Fatal error: Uncaught exception 'Exception' with message 'Missing POST Data' in /home/esokoken/public_html/PaypalIPN.php:60 Stack trace: #0 /home/esokoken/public_html/espppdtipn.php(7): PaypalIPN->verifyIPN() #1 {main} thrown in /home/esokoken/public_html/PaypalIPN.php on line 60"

Please note that the payment is successful because when I log in to my merchant account, I can see the amount paid and time paid.

Project Hosted on Linux Server

**Comment by overint** [comment]
Can you check your web server access logs, do you see the request from PayPal?
Maybe try creating a test script that saves $_POST to a file and send a sandbox IPN call to that URL to ensure that your server is properly handling post requests. 

PS. Next time you should format your issue according to [the template](https://github.com/paypal/ipn-code-samples/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by TychaK** [comment]
I get the following in the log folder

paypal_ipn_status = Completed Successfully
paypal_ipn_date = 2017-05-30 07:19:07 PDT
mc_gross = 20.00
protection_eligibility = Eligible
address_status = confirmed
payer_id = BAKEAU4ZWCB6G
address_street = 1 Main St
payment_date = 07:18:54 May 30, 2017 PDT
payment_status = Completed
charset = windows-1252
address_zip = 95131
first_name = ESoko
mc_fee = 0.88
address_country_code = US
address_name = ESoko Kenya
notify_version = 3.8
custom = 
payer_status = verified
business = work.ahcyt-selller@gmail.com
address_country = United States
address_city = San Jose
quantity = 1
verify_sign = AWtbsfOh.AspQBD5MxJnEc1oMg1HANj7qokAy1p0OtvzMLgOGJDkrXde
payer_email = work.ahcyt@gmail.com
txn_id = 1EW66905MM7976359
payment_type = instant
last_name = Kenya
address_state = CA
receiver_email = work.ahcyt-selller@gmail.com
payment_fee = 0.88
receiver_id = B96H7NVMR6T3C
txn_type = web_accept
item_name = Make Payment
mc_currency = USD
item_number = 
residence_country = US
test_ipn = 1
transaction_subject = 
payment_gross = 20.00
ipn_track_id = ebf91fd38269f

Is the above text the post data that I am suppossed to save in database then verify it with paypal?

**Comment by xiaoleih41** [comment]
Yes, it is.

**Comment by xiaoleih41** [comment]
Close due to inactivity.
