### ISSUE TITLE
Request: ASP.NET Core Web API sample

### ISSUE THREAD

**Issue by Sun3** [paypal/ipn-code-samples#94]
I would like to request a sample IPN listener for ASP.NET Core WEB API Sample. The c# code sample does not work with the new ASP.NET Core WEB API.

Thank you.

**Comment by overint** [comment]
Unfortunately I do not think any of the maintainers are c# devs, however we would welcome anyone with experience to submit a pull request that works with the new core.

**Comment by xiaoleih41** [comment]
This is a project initiative that requires substantial amount of resource.  We don't have enough information to evaluate the adoption rate as well as financial impact of this library at this time. Just like @overint had said, We welcome our developers to submit pull requests to support this new core.

**Comment by xiaoleih41** [comment]
This issue will be tracked at https://github.com/paypal/PayPal-NET-SDK/issues/146. Please follow that thread for future updates.
