### ISSUE TITLE
IPN payment_date format causes crash

### ISSUE THREAD

**Issue by Sun3** [paypal/ipn-code-samples#95]
Sandbox IPN Simulator Testing with payment_date in a php listener causes a crash. The IPN Simulator formats payment_date as ```Fri Jun 09 2017 13:20:04 GMT-0400 (EDT)```  I am assuming that in the Live environment PayPal passed the payment_date formatted the same?

I have tried to reformat data like below but no go
```
$payment_dateFormatted = date('Y-m-d h:i:s', strtotime($payment_date));
```

Any ideas? I am going to be testing with Recurring Payments and will also need to get the next_payment_date.

Thank you.

**Comment by overint** [comment]
Hi Sun

Are you using the sample provided in this repo? As far as I am aware, there is no problems with it. What error do you get?

**Comment by Sun3** [comment]
Yes, I am using the php sample in this repo. Not sure if it's the Sandbox IPN Simulator that sends the payment_date as ``` Fri Jun 09 2017 13:20:04 GMT-0400 (EDT) ``` is causing the issue. 

Testing with an actual sandbox account like mybuyersandbox@myemail.com when I make the Subscription Purchase (button created from PayPal Sandobox mymerchantsandbox@email.com account none of the dates are coming in or they are getting blanked out by the isset(...).

PaypalIPN.php
```
 public function verifyIPN()
    {
       ...
        foreach ($raw_post_array as $keyval) {
            $keyval = explode('=', $keyval);
            if (count($keyval) == 2) {
                // Since we do not want the plus in the datetime string to be encoded to a space, we manually encode it.
                if ($keyval[0] === 'payment_date') {
                    if (substr_count($keyval[1], '+') === 1) {
                        $keyval[1] = str_replace('+', '%2B', $keyval[1]);
                    }
                }
                $myPost[$keyval[0]] = urldecode($keyval[1]);
            }
        }
  ... more code...
```

Thank you

**Comment by Sun3** [comment]
Hi overint,

I retested and make a small date format change and its working perfectly. I am closing the ticket.

Thank you.
