### ISSUE TITLE
Paypal/ipn-code_open_hiddencash_flow

### ISSUE THREAD

**Issue by nbaulesglobalsolutions** [paypal/ipn-code-samples#96]
[Hidden_Cash_Flow_Deals_Blueprint.pdf](https://github.com/paypal/ipn-code-samples/files/1065981/Hidden_Cash_Flow_Deals_Blueprint.pdf)

### General information

* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by overint** [comment]
I'm not sure what this PDF contains, but it's not related to this repo and I would advise no one downloads it. Please create a new issue, follow the template and write only in plain text.
