### ISSUE TITLE
Alert handshake failure? - PHP sample

### ISSUE THREAD

**Issue by epicfaace** [paypal/ipn-code-samples#99]
### General information

* Environment: Sandbox

### Issue description

I'm getting this error that says `cURL error: [35] error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure` . It was thrown in `PayPalIPN.php:124`. I was using the Paypal IPN sandbox to send calls, and the sandbox reported that the call was successful. However, when I check the server logs, I am getting this cURL error.

**Comment by pp-randy** [comment]
SSL version 3 isn't supported, you should use TLS 1.2.

**Comment by overint** [comment]
Randy is correct. What version of PHP are you running? As long as you have not modified the script, it should force TLS 1.2

**Comment by overint** [comment]
This has been open for a while, could you let me know if this is solved?

**Comment by epicfaace** [comment]
Yes, thanks @overint and @pp-randy . The problem was an outdated version of PHP.

**Comment by overint** [comment]
Thanks, glad you got it fixed.
